2024-10-25 19:06:48,021 ERROR: Exception on /reset_password_request [POST] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 207, in reset_password_request
    send_password_reset_emai(user)
    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'send_password_reset_emai' is not defined. Did you mean: 'send_password_reset_email'?
2024-10-25 19:07:35,194 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:07:48,620 ERROR: Exception on /reset_password_request [POST] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 207, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/models.py", line 92, in get_reset_password_token
    return jwt.encode(
           ^^^^^^^^^^^
TypeError: PyJWT.encode() got an unexpected keyword argument 'algorithms'
2024-10-25 19:09:51,409 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:09:59,459 ERROR: Exception on /reset_password_request [POST] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 207, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/email.py", line 23, in send_password_reset_email
    recipients=[user.emai],
                ^^^^^^^^^
AttributeError: 'User' object has no attribute 'emai'. Did you mean: 'email'?
2024-10-25 19:13:07,563 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:13:22,282 ERROR: Exception on /reset_password_request [POST] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 207, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/email.py", line 26, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/templates/email/reset_password.html", line 11, in template
    <p>{{ url_for('reset_password', token=token, _external_true) }}</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: invalid syntax for function call expression
2024-10-25 19:16:38,352 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:18:03,928 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzI5ODk4ODE0LjgwODk0MTF9.QrpUZGA-tVmIP8esc2alQ-Kyiepjm4XnT-XuKCO1nd4 [GET] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 217, in reset_password
    user = User.verify_reset_password_token(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'User' has no attribute 'verify_reset_password_token'. Did you mean: 'get_reset_password_token'?
