2024-10-25 19:21:35,887 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:22:13,139 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzI5ODk5MTE4Ljc5Njk4NTF9.KQn3vVa6MhIa_HjwibN3qba-PZ9eqxCiT7MbB4cgEb8 [GET] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 218, in reset_password
    user = User.verify_reset_password(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/models.py", line 102, in verify_reset_password
    return db.session(User, id)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: scoped_session.__call__() takes 1 positional argument but 3 were given
2024-10-25 19:25:13,582 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 19:25:46,396 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzI5ODk5MzI5LjU4MzM0OX0.rDDeqdNhrK8ODUBPGnGAGlL3jjlscZ8EtgmEmKNMKoo [GET] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 227, in reset_password
    return render_template('reset_password.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/templates/reset_password.html", line 6, in block 'content'
    {{ from.hidden_tag() }}
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'from' is undefined
2024-10-25 19:33:26,968 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 20:54:03,850 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzI5OTA0NjIwLjM3MzEyNDF9.fNPHVRe8iqHkteBnl_4v6Ko7Yv4QSL8Gc8JIEOnknFY [GET] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 218, in reset_password
    user = User.verify_reset_password(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/models.py", line 102, in verify_reset_password
    return db.session(User, id)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: scoped_session.__call__() takes 1 positional argument but 3 were given
2024-10-25 21:01:28,829 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 21:25:27,558 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
2024-10-25 21:26:19,283 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNzI5OTA2NTUyLjc3NjI0Mn0.n_8zJ-8X4ljLMYAEpEnf49wsFstuBBrK1qziRATcPRw [GET] [in /Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/routes.py", line 217, in reset_password
    user = User.verify_reset_password_token(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anatoliykayola/python/microblog/venv/microblog/app/models.py", line 103, in verify_reset_password_token
    return db.session(User, id)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: scoped_session.__call__() takes 1 positional argument but 3 were given
2024-10-25 21:29:18,651 INFO: Microblog startup [in /Users/anatoliykayola/python/microblog/venv/microblog/app/__init__.py:45]
